CREATE TABLE STATS (
	STAT_ID INT(11) NOT NULL AUTO_INCREMENT,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL,
    PRIMARY KEY (STAT_ID)
    );
    
CREATE VIEW BESTSELLERS_COUNT AS
	SELECT COUNT(*) AS BESTSELLERS_COUNTER FROM books
     WHERE BESTSELERS = 1;

DELIMITER $$

CREATE PROCEDURE BestsellerEventProcedure()
BEGIN
	DECLARE BESTSELLERS_COUNTER_VAR INT DEFAULT 0;
    
    CALL UpdateBestsellers();
      
    SELECT BESTSELLERS_COUNTER FROM BESTSELLERS_COUNT INTO BESTSELLERS_COUNTER_VAR;
    
    INSERT INTO STATS (STAT_DATE, STAT, VALUE)
    VALUES (CURTIME(), "BESTSELLERS", BESTSELLERS_COUNTER_VAR);
END $$

DELIMITER ;

CREATE EVENT BESTSELLERS_EVENT
	ON SCHEDULE EVERY 1 MINUTE
    DO CALL BestsellerEventProcedure();
