CREATE INDEX BOOKSINDEX ON BOOKS (TITLE);
CREATE INDEX FIRSTNAMEINSEX ON READERS (FIRSTNAME);
CREATE INDEX LASTNAMEINSEX ON READERS (LASTNAME);

EXPLAIN SELECT COUNT(*)
FROM READERS
WHERE FIRSTNAME = "John";